CREATE TABLE `tree_dict`
(
    `id`                 varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci   NOT NULL COMMENT '主键（业务主键）',
    `parent_id`          varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci   NOT NULL COMMENT '上级 id',
    `namespace`          varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci   NOT NULL COMMENT '命名空间',
    `code`               varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci   NOT NULL COMMENT '数据代码',
    `description`        varchar(4096) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '数据描述',
    `left_value`         bigint(20) unsigned                                            NOT NULL COMMENT '左值',
    `right_value`        bigint(20) unsigned                                            NOT NULL COMMENT '右值',
    `depth`              bigint(20) unsigned                                            NOT NULL COMMENT '深度',
    `path`               varchar(4096) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '路径',
    `auth_user_id`       varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci            DEFAULT NULL COMMENT '授权访问用户',
    `auth_role_id`       varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci            DEFAULT NULL COMMENT '授权访问角色',
    `auth_dept_id`       varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci            DEFAULT NULL COMMENT '授权访问部门',
    `auth_org_id`        varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci            DEFAULT NULL COMMENT '授权访问机构',
    `last_modified_by`   varchar(32)                                                    NOT NULL COMMENT '上次修改用户',
    `last_modified_time` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci   NOT NULL COMMENT '上次修改时间',
    `created_by`         varchar(32)                                                    NOT NULL COMMENT '创建用户',
    `created_time`       varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci   NOT NULL COMMENT '创建时间',
    `deleted_flag`       bigint(20) unsigned                                            NOT NULL DEFAULT '0' COMMENT '逻辑删除标志位',
    `version`            bigint(20) unsigned                                            NOT NULL COMMENT '版本',
    PRIMARY KEY (`id`),
    UNIQUE KEY `tree_dict_union_unique_1` (`namespace`, `code`, `deleted_flag`) USING BTREE COMMENT '同一命名空间下code值必须唯一',
    KEY `tree_dict_auth_user_id` (`auth_user_id`) USING HASH COMMENT '授权访问用户索引',
    KEY `tree_dict_last_modified_time` (`last_modified_time`) USING BTREE COMMENT '上次修改时间索引',
    KEY `tree_dict_last_modified_by` (`last_modified_by`) USING HASH COMMENT '上次修改用户索引',
    KEY `tree_dict_created_time` (`created_time`) USING BTREE COMMENT '创建时间索引',
    KEY `tree_dict_created_by` (`created_by`) USING HASH COMMENT '创建用户索引',
    KEY `tree_dict_deleted_flag` (`deleted_flag`) USING BTREE COMMENT '逻辑删除标志位索引',
    KEY `tree_dict_left` (`left_value`) USING BTREE COMMENT '树形字典左值索引',
    KEY `tree_dict_right` (`right_value`) USING BTREE COMMENT '树形字典右值索引',
    KEY `tree_dict_namespace` (`namespace`) USING HASH COMMENT '命名空间索引'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;